create whitelist hash:net family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x43157af6
add whitelist 127.0.0.1
add whitelist 196.179.222.182
add whitelist 81.95.124.0/26
add whitelist 213.144.214.192/26
add whitelist 197.2.57.251
add whitelist 81.95.119.128/26
create ssh hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x77bbc924
create sip hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x0160c2d9
create db hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0xc3fc6a70
create web hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x5ba3114b
create proxy hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0xaef0439d
create email hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0x6ae63b96
create blacklist hash:ip family inet hashsize 1024 maxelem 65536 bucketsize 12 initval 0xbfae05f7